export const texts = {
    STAR_WARS_EXPLORER: 'Star Wars Explorer',
    STAR_WARS_MOVIES_CATALOG: 'Star Wars Movies Catalog',
    AN_ERROR_OCCURRED_WHILE_FETCHING_FILMS: 'An error occurred while fetching films',
    ERROR_FETCHING_FILMS: 'Error fetching films',
    AN_UNKNOWN_ERROR_OCCURRED: 'An unknown error occurred',
    HOME: 'Home',
    RELEASE_DATE_PREFIX: "Release Date - ",
    DIRECTOR_LABEL: "Director:",
    PRODUCER_LABEL: "Producer:",
    CHARACTERS_ACCORDION_TITLE: "Characters",
    ERROR_FETCHING_CHARACTER: 'Error fetching character:',
    HEIGHT: 'Height',
    MASS: 'Mass',
    HAIR_COLOR: 'Hair Color',
    SKIN_COLOR: 'Skin Color',
    EYE_COLOR: 'Eye Color',
    BIRTH_YEAR: 'Birth Year',
    ERROR_FETCHING_VEHICLE: "An error occurred while fetching vehicle details.",
    VEHICLE_NAME: "Name",
    VEHICLE_MODEL: "Model",
    VEHICLE_MANUFACTURER: "Manufacturer",
    VEHICLE_COST: "Cost (in credits)",
    VEHICLE_LENGTH: "Length",
    VEHICLE_MAX_SPEED: "Max Speed",
    VEHICLE_CREW: "Crew",
    VEHICLE_PASSENGERS: "Passengers",
    VEHICLE_CARGO_CAPACITY: "Cargo Capacity",
    VEHICLE_CONSUMABLES: "Consumables",
    VEHICLE_CLASS: "Vehicle Class",
    ERROR_FETCHING_STARSHIP: "An error occurred while fetching starship details.",
    STARSHIP_NAME: "Name",
    STARSHIP_MODEL: "Model",
    STARSHIP_MANUFACTURER: "Manufacturer",
    STARSHIP_COST: "Cost (in credits)",
    STARSHIP_LENGTH: "Length",
    STARSHIP_MAX_SPEED: "Max Speed",
    STARSHIP_CREW: "Crew",
    STARSHIP_PASSENGERS: "Passengers",
    STARSHIP_CARGO_CAPACITY: "Cargo Capacity",
    STARSHIP_CONSUMABLES: "Consumables",
    STARSHIP_HYPERDRIVE_RATING: "Hyperdrive Rating",
    STARSHIP_CLASS: "Starship Class",
    ERROR_FETCHING_SPECIES: "An error occurred while fetching species details.",
    SPECIES_NAME: "Name",
    SPECIES_CLASSIFICATION: "Classification",
    SPECIES_DESIGNATION: "Designation",
    SPECIES_AVERAGE_HEIGHT: "Average Height",
    SPECIES_SKIN_COLORS: "Skin Colors",
    SPECIES_HAIR_COLORS: "Hair Colors",
    SPECIES_EYE_COLORS: "Eye Colors",
    SPECIES_AVERAGE_LIFESPAN: "Average Lifespan",
    SPECIES_HOMEWORLD: "Homeworld",
    SPECIES_LANGUAGE: "Language",
}